app/comments/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired


class CommentForm(FlaskForm):
    description = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

app/comments/routes.py
from flask import Blueprint, flash, url_for, redirect, render_template
from flask_login import login_required, current_user

from app.comments.forms import CommentForm
from app.models import Comment
from app import db

from app.models import Pitch

comments = Blueprint('comments', __name__)

@comments.route('/add_comment/<int:pitch_id>', methods = ['GET', 'POST'])
@login_required
def add_comment(pitch_id):
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(pitch_id = pitch_id, description =form.description.data,
                      author=current_user)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment was added!', 'success')
        return redirect(url_for('main.home'))
    return render_template('add_comment.html', form=form)

@comments.route('/view_comments/<int:pitch_id>')
def view_comments(pitch_id):
    pitch = Pitch.query.get(pitch_id)
    users_comments = pitch.comments
    print(users_comments)
    return render_template('comments.html', comments = users_comments)

app/pitches/routes.py
from flask import Blueprint, flash, url_for, render_template, redirect
from flask_login import login_required, current_user

from app import db
from app.models import Pitch
from app.pitches.forms import PitchForm

pitches = Blueprint('pitches', __name__)


@pitches.route('/pitch/new', methods =['GET', 'POST'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        pitch = Pitch(title=form.title.data, content=form.content.data, category= form.category.data, author=current_user)
        db.session.add(pitch)
        db.session.commit()
        flash('Your pitch has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('add_pitch.html', form = form)

app/users/routes.py
from flask import Blueprint, request
from flask_login import current_user, login_user, logout_user, login_required
from flask import redirect, url_for, render_template, flash

from app import bcrypt, db
from app.models import User
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm

users = Blueprint('users',__name__)


@users.route('/register', methods =['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form = form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        print(user)
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods = ['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    user_avatar = url_for('static', filename='profile_avatars/' + current_user.image_file)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', user_avatar = user_avatar, form = form)

app/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{user_avatar}}">
        <div class="media-body">
          <h2 class="account-heading">{{current_user.username}}</h2>
          <p class="text-secondary">{{current_user.email}}</p>
        </div>
      </div>
      <form action="" method="Post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Your Profile</legend>
                <div class="form-group">
                    {{form.username.label(class="form-control-label")}}
                    {% if form.username.errors %}
                        {{form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.username(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/add_comment.html
{%extends 'layout.html'%}
{% block content%}
    <div class="content-section">
        <form action="" method="Post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">add comment</legend>
                 <div class="form-group">
                    {{form.description.label(class="form-control-label")}}
                    {% if form.description.errors %}
                        {{form.title(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.description.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.description(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/add_pitch.html
{%extends 'layout.html'%}
{% block content%}
    <div class="content-section">
        <form action="" method="Post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add pitch</legend>
                 <div class="form-group">
                    {{form.title.label(class="form-control-label")}}
                    {% if form.title.errors %}
                        {{form.title(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.title(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{form.content.label(class="form-control-label")}}
                     {% if form.content.errors %}
                        {{form.content(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                     {% else %}
                        {{form.content(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                  <div class="form-group">
                    {{form.category.label(class="form-control-label")}}
                     {% if form.category.errors %}
                        {{form.category(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.category.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                     {% else %}
                        {{form.category(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/comments.html
{% extends 'layout.html'%}
{% block content%}
    {% for comment in comments%}
        <div class="card w-75">
          <div class="card-body">
            <h5 class="card-title">{{comment.description}}</h5>
            <p class="card-text">{{comment.author.username}}</p>
            <a href="{{url_for('main.home')}}" class="btn btn-primary">Back Home</a>
          </div>
        </div>
    {% endfor %}
{% endblock%}

app/templates/create_pitch.html
{%extends 'layout.html'%}
{% block content%}
    <div class="content-section">
        <form action="" method="Post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create pitch</legend>
                 <div class="form-group">
                    {{form.title.label(class="form-control-label")}}
                    {% if form.title.errors %}
                        {{form.title(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.title(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{form.content.label(class="form-control-label")}}
                     {% if form.content.errors %}
                        {{form.content(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                     {% else %}
                        {{form.content(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                  <div class="form-group">
                    {{form.category.label(class="form-control-label")}}
                     {% if form.category.errors %}
                        {{form.category(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.category.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                     {% else %}
                        {{form.category(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}
{% block content%}
    {% for pitch in pitches %}
          <div>
                <div class="card my-5" style="max-width: 700px;">
                  <div class="card-header">
                    <h5 class="card-title">{{ pitch.title }}</h5>
                  </div>
                  <div class="card-body">
                      <p class="card-text">{{pitch.content}}</p>
                      <div>
                        <a href="{{url_for('comments.add_comment',pitch_id = pitch.id)}}" class="btn btn-outline-primary d-inline mr-3">Comment</a>
                        <h4 class="card-text d-inline mr-3"><small class="text-muted"><a href="{{url_for('main.home', pitch_id = pitch.id, like = 'like')}}"><i class="fa fa-thumbs-up"></i></a> {{ pitch.upvote }}</small></h4>
                        <h4 class="card-text d-inline mr-3"><small class="text-muted"><a href="{{url_for('main.home', pitch_id = pitch.id, like = 'dislike')}}"><i class="fa fa-thumbs-down"></i></a> {{ pitch.downvote }}</small></h4>
                        <a href="{{url_for('comments.view_comments',pitch_id = pitch.id, users_comments = pitch.comments)}}" class="btn btn-outline-secondary d-inline mr-3">View Comments</a>
                      </div>
                  </div>
                </div>
          </div>
    {% endfor %}
{% endblock%}
{% block sidebar %}
    <div class="content-section my-5">
        <h3>Categories </h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"> <a href="{{url_for('main.home')}}"><span style=" content: '\2713';">&#10003;</span> All</a></li>
                <li class=" list-group-item"> <a href="{{url_for('main.home', category = 'health')}}"><span style=" content: '\2713';">&#10003;</span> Health</a></li>
                <li class=" list-group-item"> <a href="{{url_for('main.home', category = 'diet')}}"><span style=" content: '\2713';">&#10003;</span> Diet</a></li>
                <li class="list-group-item"> <a href="{{url_for('main.home', category = 'exercise')}}"><span style=" content: '\2713';">&#10003;</span> Exercise</a></li>
            </ul>
        </p>
    </div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename = 'main.css')}}">
    <title>Title</title>
</head>
<body>
     <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">One minute Pitch</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{url_for('pitches.new_pitch')}}">Add a Pitch</a>
                  <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                  <a class="nav-item nav-link" href="{{url_for('users.account')}}">{{current_user.username}}</a>
              {% else %}
                  <a class="nav-item nav-link" href="/login">Login</a>
                  <a class="nav-item nav-link" href="/register">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
     <main role="main" class="container">
        <div class="row">
            <div class="col-md-3">
                {% block sidebar %}
                {% endblock %}
            </div>
            <div class="col-md-9">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages%}
                        <div class="alert alert-{{category}}">
                            {{message}}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/be3e9fc394.js"></script>
</body>
</html>

app/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

app/templates/macro.html
{% macro display(category_list) %}
<div class="row">
    {% if category_list %}
    {% for category in category_list %}
    <div class="col-md-6" style="box-shadow: 2px 4px 12px 2px rgb(148, 147, 147); margin: 1rem; padding: 0; border-radius: 10px; margin-bottom: 20px;">

        <div class="text-center">
            <p>Title:{{category.title}}</p>
            <p>Category:{{category.category}}</p>

            <blockquote>
                <h2{{category.description}}</h2>
                <footer class="blockquote-footer"> Posted by {{category.user.username}}</footer>
            </blockquote>

            <a href="{{url_for('main.new_comment',pitch_id = category.id)}}" class="btn btn-info"> Add a comment</a>

            <a href="{{url_for('main.upvote',pitch_id = category.id)}}" class="btn btn-success btn-sm"><i></i>Upvote
                <span>{{category.upvotes.count()}}</span></a>
            <a href="{{url_for('main.downvote',pitch_id = category.id)}}" class="btn btn-danger btn-sm"><i class="far fa-thumbs-up"></i>Downvote
                <span>{{category.downvotes.count()}}</span></a>

        </div>

    </div>
    {% endfor %}
    {% else %}
    {% endif %}
</div>
{% endmacro %}

{% macro displayComment(comments) %}
<ul>

    {% if comments %}
    {% for comment in comments %}
    <div class="row text-center" style="margin-bottom:20px;">
        <a>
            <p style="color: rgb(10, 10, 10);">{{ comment.description }}</p>
        </a>
        <small> posted by {{comment.user.username}}</small>
    </div>
    {% endfor %}
    {% else %}

    <h3>This post does not does not have any comments yet !</h3>
    {%endif%}

</ul>

{% endmacro %}

app/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="#">Sign In</a>
        </small>
    </div>
{% endblock content %}